### ISSUE TITLE
Required resources and time for training

### ISSUE THREAD

**Issue by Wang-pengfei** [lyhdet/OV-3DET#1]
Hello

Thanks for your inspiring work.
Is the current code complete and ready for running?  And what GPU do you use and how long does it take to finish training?

**Comment by lyhdet** [comment]
It takes ~48 hours for Phase 1 (Learning to Localize 3D Objects), ~24 hours for Phase 2 (Learning to Classify 3D Objects), which tests under an 8x2080Ti GPU Server.
