### ISSUE TITLE
Question About Model Architecture

### ISSUE THREAD

**Issue by hongxiaoy** [lyhdet/OV-3DET#2]
Thanks for your work in 3D detection field! And I was stuck in understanding the method.

1. Is this model a two stage method?
2. How is the pseudo boxes' parameters calculated from the remaining points in phase 1?
3. Is the pseudo box served as the ground truth box of 3DETR in phase 1?
4. Will L_{loc} updated the model architecture, or is it be stopped to back propagate the gradient?

Those are my questions, wish your reply~

Thanks for your work again!

**Comment by lyhdet** [comment]
Thank you for your interest in our work! I'm glad to answer your questions and provide additional information:

1. OV-3DET is built upon 3DETR, which is a one-stage 3D detector.
2. To determine the orientation, we utilize PCA, followed by a tighten box to cover the remaining points. For more detailed information, you can refer to: [https://github.com/lyhdet/OV-3DET/blob/main/Data_Maker/Pseudo_Label_Maker/scannet_util.py].
3. Yes, during phase 1, the pseudo boxes are employed as ground truth boxes for our 3DETR model.
4. In both phase 1 and 2, we enable L_{loc}, which significantly contributes to the model's performance.

If you have more questions, feel free to ask!
