### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by JinmoKIM1012** [lyhdet/OV-3DET#3]
Hello,

Thank you for your impressive work! 

I'm trying to visualize the inference demo of the OV-3DET, but it seems there is no explanation for visualizing the results in the documentation. 
Could you give me an explanation about the visualization of qualitative results?

**Comment by lyhdet** [comment]
Thank you for your interest in our work!

We're actively working on the visualization part. For a quick attempt, follow the instructions at: [https://github.com/facebookresearch/votenet/tree/main/sunrgbd]

If you have more questions, feel free to ask!

**Comment by YoujunZhao** [comment]
Did you solve the problem? I'm also trying to visualize the predicted 3D bounding box in the inference stage. I have visualized the pseudo 3D bounding box, but I can't visualize the predicted 3D bounding box. Or could you please release the visualization code? Thanks!
